INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Title", "Category", 4000, "Monday", "Tuesday");
INSERT INTO users (id, name, age) VALUES (1, "Name", 37);
INSERT INTO users (id, name, age) VALUES (2, "Name", 37);
INSERT INTO users (id, name, age) VALUES (3, "Name", 37);
INSERT INTO users (id, name, age) VALUES (4, "Name", 37);
INSERT INTO users (id, name, age) VALUES (5, "Name", 37);
INSERT INTO users (id, name, age) VALUES (6, "Name", 37);
INSERT INTO users (id, name, age) VALUES (7, "Name", 37);
INSERT INTO users (id, name, age) VALUES (8, "Name", 37);
INSERT INTO users (id, name, age) VALUES (9, "Name", 37);
INSERT INTO users (id, name, age) VALUES (10, "Name", 37);
INSERT INTO users (id, name, age) VALUES (11, "Name", 37);
INSERT INTO users (id, name, age) VALUES (12, "Name", 37);
INSERT INTO users (id, name, age) VALUES (13, "Name", 37);
INSERT INTO users (id, name, age) VALUES (14, "Name", 37);
INSERT INTO users (id, name, age) VALUES (15, "Name", 37);
INSERT INTO users (id, name, age) VALUES (16, "Name", 37);
INSERT INTO users (id, name, age) VALUES (17, "Name", 37);
INSERT INTO users (id, name, age) VALUES (18, "Name", 37);
INSERT INTO users (id, name, age) VALUES (19, "Name", 37);
INSERT INTO users (id, name, age) VALUES (20, "Name", 37);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(1, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(2, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(3, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(4, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(5, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(6, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(7, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(8, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(9, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(10, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(11, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(12, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(13, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(14, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(15, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(16, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(17, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(18, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(19, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(20, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(21, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(22, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(23, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(24, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(25, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(26, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(27, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(28, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(29, 300, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES(30, 300, 1, 2);
